// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWSN10MxFuoMUwIRnOCp9VvK8UcZNLYbY',
    appId: '1:737420532156:web:8e2c0ed00aa6c4d3d673b9',
    messagingSenderId: '737420532156',
    projectId: 'colormatch-12f8b',
    authDomain: 'colormatch-12f8b.firebaseapp.com',
    storageBucket: 'colormatch-12f8b.appspot.com',
    measurementId: 'G-RE5E7HGNQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrL76BTRDOq6Kge4iiH9Lthjxl0GE44Vs',
    appId: '1:737420532156:android:cea76af8ef32352bd673b9',
    messagingSenderId: '737420532156',
    projectId: 'colormatch-12f8b',
    storageBucket: 'colormatch-12f8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBcerHlu-Ydc-MImfp-VNhl98-yrte0g',
    appId: '1:737420532156:ios:9ba17859c6164d97d673b9',
    messagingSenderId: '737420532156',
    projectId: 'colormatch-12f8b',
    storageBucket: 'colormatch-12f8b.appspot.com',
    iosBundleId: 'com.example.colorMatchGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeBcerHlu-Ydc-MImfp-VNhl98-yrte0g',
    appId: '1:737420532156:ios:9ba17859c6164d97d673b9',
    messagingSenderId: '737420532156',
    projectId: 'colormatch-12f8b',
    storageBucket: 'colormatch-12f8b.appspot.com',
    iosBundleId: 'com.example.colorMatchGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWSN10MxFuoMUwIRnOCp9VvK8UcZNLYbY',
    appId: '1:737420532156:web:e6ba5d68a8456654d673b9',
    messagingSenderId: '737420532156',
    projectId: 'colormatch-12f8b',
    authDomain: 'colormatch-12f8b.firebaseapp.com',
    storageBucket: 'colormatch-12f8b.appspot.com',
    measurementId: 'G-LM1742H4YE',
  );

}